/*
*           MariaDB Initialization Queries
*/
-- database and user creation
CREATE DATABASE library DEFAULT CHARACTER SET = 'ascii';
CREATE USER librarian IDENTIFIED BY 'babel';
GRANT ALL PRIVILEGES ON library.* to 'librarian';
-- tables creation
USE library;
CREATE TABLE Livros (id INT AUTO_INCREMENT PRIMARY KEY, isbn13 CHAR(13) UNIQUE NOT NULL, Editoras_id INT NOT NULL, titulo VARCHAR(255) NOT NULL, subtitulo VARCHAR(255), idioma CHAR(4) NOT NULL, lancamento DATE NOT NULL, descricao TEXT);
CREATE TABLE Editoras (id INT AUTO_INCREMENT PRIMARY KEY, cnpj CHAR(14) NOT NULL UNIQUE, razao_social VARCHAR(255) UNIQUE NOT NULL, nome VARCHAR(255) NOT NULL, fundacao DATE NOT NULL);
CREATE TABLE Editoras_enderecos (id INT AUTO_INCREMENT PRIMARY KEY, Editoras_id INT NOT NULL, cep CHAR(8) NOT NULL, logradouro VARCHAR(255) NOT NULL, numero VARCHAR(255) NOT NULL, complemento VARCHAR(255), bairro VARCHAR(255) NOT NULL, cidade VARCHAR(255) NOT NULL, estado CHAR(2) NOT NULL);
CREATE TABLE Editoras_contatos (id INT AUTO_INCREMENT PRIMARY KEY, Enderecos_id INT NOT NULL, nome VARCHAR(255) NOT NULL, ddd CHAR(2) NOT NULL, numero VARCHAR(9) NOT NULL, email VARCHAR(255));
CREATE TABLE Tag (Generos_id INT NOT NULL, Livros_id INT NOT NULL);
CREATE TABLE Generos (id INT AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(255) NOT NULL, descricao TEXT NOT NULL);
CREATE TABLE Autoria (Livros_id INT NOT NULL, Autores_id INT NOT NULL);
CREATE TABLE Autores (id INT AUTO_INCREMENT PRIMARY KEY, cpf CHAR(11) UNIQUE NOT NULL, nome VARCHAR(255) NOT NULL, pseudonimo VARCHAR(255), email VARCHAR(255));
CREATE TABLE Caracteristicas_fisicas (Livros_id INT AUTO_INCREMENT PRIMARY KEY, altura VARCHAR(3) NOT NULL, largura VARCHAR(3) NOT NULL, comprimento VARCHAR(3) NOT NULL, paginas VARCHAR(6) NOT NULL, capa_dura BOOLEAN NOT NULL);
-- adding foreign keys
ALTER TABLE Livros ADD CONSTRAINT FOREIGN KEY (Editoras_id) REFERENCES Editoras (id) ON UPDATE  NO ACTION  ON DELETE  CASCADE;
ALTER TABLE Editoras_enderecos ADD CONSTRAINT FOREIGN KEY (Editoras_id) REFERENCES Editoras (id) ON UPDATE  NO ACTION  ON DELETE  CASCADE;
ALTER TABLE Editoras_contatos ADD CONSTRAINT FOREIGN KEY (Enderecos_id) REFERENCES Editoras_enderecos (id) ON UPDATE  NO ACTION  ON DELETE  CASCADE;
ALTER TABLE Tag ADD CONSTRAINT FOREIGN KEY (Generos_id) REFERENCES Generos (id) ON UPDATE  NO ACTION  ON DELETE  CASCADE;
ALTER TABLE Tag ADD CONSTRAINT FOREIGN KEY (Livros_id) REFERENCES Livros (id) ON UPDATE  NO ACTION  ON DELETE  CASCADE;
ALTER TABLE Autoria ADD CONSTRAINT FOREIGN KEY (Livros_id) REFERENCES Livros (id) ON UPDATE  NO ACTION  ON DELETE  CASCADE;
ALTER TABLE Autoria ADD CONSTRAINT FOREIGN KEY (Autores_id) REFERENCES Autores (id) ON UPDATE  NO ACTION  ON DELETE  CASCADE;
ALTER TABLE Caracteristicas_fisicas ADD CONSTRAINT FOREIGN KEY (Livros_id) REFERENCES Livros (id) ON UPDATE  NO ACTION  ON DELETE  CASCADE;